# config.toml

[generate]
projectLocalPath = "C:\\Users\\admin\\Desktop\\实战\\JavaCodeGenerate\\SpingBootSimpleTemplate" # java项目根目录路径

isGenerateController = true # 是否生成controller控制器层代码
isGenerateService = true # 是否生成service层代码
isGenerateEntity = true # 是否生成entity层实体类代码

# 如果需要自定义生成代码的路径可以在下面配置，不自定义忽视即可
ControllerGenerateLocalPath = "" # 存放controller控制器层代码生成的本地路径
ServiceGenerateLocalPath = "" # 存放service层代码生成的本地路径
EntityGenerateLocalPath = "" # 存放entity层实体类代码生成的本地路径


[database]
url = "localhost" # 数据库url
port = 3306
username = "root" # 数据库用户名
password = "311252" # 数据库密码
dbname = "template" # 数据库名称