# config.toml

[generate]
projectLocalPath = "C:\\Users\\admin\\Desktop\\实战\\JavaCodeGenerate\\SpingBootSimpleTemplate" # java项目根目录路径

isGenerateController = true # 是否生成controller控制器层代码 默认为true
isGenerateService = true # 是否生成service层代码 默认为true
isGenerateEntity = true # 是否生成entity层实体类代码 默认为true

# 代码会自动在正确的项目结构生成对应层的代码，如果需要自定义生成代码的路径可以在下面配置，不自定义忽视即可
ControllerGenerateLocalPath = "" # 存放controller控制器层代码生成的本地路径
ServiceGenerateLocalPath = "C:\\Users\\admin\\Desktop\\实战\\JavaCodeGenerate\\SpingBootSimpleTemplate\\target" # 存放service层代码生成的本地路径
EntityGenerateLocalPath = "" # 存放entity层实体类代码生成的本地路径

# 排除列表 在生成过程中不希望再重新生成或修改特定文件的列表 默认为空列表 用,号分隔
ExclusionList = []

[database]
url = "localhost" # 数据库url
port = 3306
username = "root" # 数据库用户名
password = "311252" # 数据库密码
dbname = "template" # 数据库名称

# 数据库类型转为java类型的映射表
[convert]
